### ISSUE TITLE
[BUG REPORT]  game crashing when clicking the config button - not working

### ISSUE THREAD

**Issue by MarkinhosMLP** [burgerguy/HUDTweaks#22]
java.lang.IllegalStateException: Start called twice in a row
	at Not Enough Crashes deobfuscated stack trace.(1.17.1+build.61)
	at com.github.burgerguy.hudtweaks.util.gl.DrawTest.markStart(DrawTest.java:25)
	at com.github.burgerguy.hudtweaks.hud.element.HudElementContainer.markDrawTestStart(HudElementContainer.java:123)
	at com.github.burgerguy.hudtweaks.util.RenderStateUtil.startRender(RenderStateUtil.java:22)
	at com.github.burgerguy.hudtweaks.util.RenderStateUtil.startRender(RenderStateUtil.java:16)
	at net.minecraft.client.gui.hud.BossBarHud.handler$bji000$renderBossBarHead(BossBarHud:1517)
	at net.minecraft.client.gui.hud.BossBarHud.render(BossBarHud)
	at net.minecraft.client.gui.hud.InGameHud.redirect$cia000$onRenderBossBarsInRender(InGameHud:10082)
	at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:254)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:1217)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1117)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:733)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$cdm000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:23046)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$cdm000$atTheEndOfSecondCatchBeforePrintingCrashReport(MinecraftClient:23046)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:760)
	at fudge.notenoughcrashes.mixinhandlers.InGameCatcher.handleClientCrash(InGameCatcher.java:37)
	at net.minecraft.client.MinecraftClient.modify$cdm000$atTheEndOfFirstCatchBeforePrintingCrashReport(MinecraftClient:23035)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:755)
	at net.minecraft.client.main.Main.main(Main:238)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:608)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- Head --
Thread: Render thread
Stacktrace:
	at com.github.burgerguy.hudtweaks.util.gl.DrawTest.markStart(DrawTest.java:25)
	at com.github.burgerguy.hudtweaks.hud.element.HudElementContainer.markDrawTestStart(HudElementContainer.java:123)
	at com.github.burgerguy.hudtweaks.util.RenderStateUtil.startRender(RenderStateUtil.java:22)
	at com.github.burgerguy.hudtweaks.util.RenderStateUtil.startRender(RenderStateUtil.java:16)
	at net.minecraft.class_337.handler$bji000$renderBossBarHead(class_337.java:1517)
	at net.minecraft.class_337.method_1796(class_337.java)
	at net.minecraft.class_329.redirect$cia000$onRenderBossBarsInRender(class_329.java:10082)
	at net.minecraft.class_329.method_1753(class_329.java:254)

**Comment by burgerguy** [comment]
Can you post your mods list? It isn't crashing for me but other people seem to have problems with it.

**Comment by MarkinhosMLP** [comment]
1.18.1 - Fabric
Every single mod in it is Client-Sided only

![image](https://user-images.githubusercontent.com/47507632/153323781-73f7f0ca-e3af-44b0-834e-ec9dda058cfb.png)
![image](https://user-images.githubusercontent.com/47507632/153323846-5cc32dd7-b2b8-4643-ba7b-60b4ac3ce35e.png)
![image](https://user-images.githubusercontent.com/47507632/153323878-9790c9f7-bc3b-4bd2-a108-28f45d5035a4.png)
![image](https://user-images.githubusercontent.com/47507632/153323919-af3a9a55-e9ac-4a7a-b1f2-a2e688cd2313.png)
![image](https://user-images.githubusercontent.com/47507632/153323982-b1270328-d3c6-48b7-84ef-abc60d1bbf8e.png)
![image](https://user-images.githubusercontent.com/47507632/153324015-f54da848-00ba-4916-a056-ad8fb27e3188.png)

**Comment by burgerguy** [comment]
Could you package and send a link to all of the mods for testing? I can't reasonably fix it without all of them.

**Comment by MarkinhosMLP** [comment]
okay then, imma upload it in mediafire cause for some reason i cant send it directly here
https://www.mediafire.com/file/vwjzhyhfj6uz7ow/mods.zip/file

**Comment by MarkinhosMLP** [comment]
oh yeaaaaaah, fixed TYSM ♥
