### ISSUE TITLE
Incompatibility Issue with Skyblocker Mod for Hypixel

### ISSUE THREAD

**Issue by jmdev91** [burgerguy/HUDTweaks#25]
https://github.com/burgerguy/HUDTweaks/blob/91409b72ef77430971a5850ff27838a859feef59/src/main/java/com/github/burgerguy/hudtweaks/hud/element/HudElementContainer.java#L118
This method seems to be triggering a crash when this mod is used alongside the [Skyblocker Mod](https://github.com/SkyblockerMod/Skyblocker) for Hypixel. It appears to be a situation where the internal tracking of whether a matrix has been pushed/popped is skipped somewhere along the line. That mod changes how the experience bar is rendered to show modded server information about health, mana, and armor together with experience in a few different layouts. The two work together fine at first, but as soon as Skyblocker is set to turn off its features, this mod crashes when it attempts to render. This happens when exiting to the main menu from the Skyblock game mode of Hypixel and loading back into the lobby as well as when returning to the lobby from within Skyblock.

The NEC-Deobfuscated Stack Trace:
java.util.NoSuchElementException
    at Not Enough Crashes deobfuscated stack trace.(1.18.2+build.3)
    at java.util.ArrayDeque.getLast(Unknown Source)
    at net.minecraft.client.util.math.MatrixStack.peek(MatrixStack:65)
    at net.minecraft.client.gui.DrawableHelper.drawTexture(DrawableHelper:205)
    at net.minecraft.client.gui.DrawableHelper.drawTexture(DrawableHelper:177)
    at net.minecraft.client.gui.DrawableHelper.drawTexture(DrawableHelper:166)
    at net.minecraft.client.gui.hud.InGameHud.renderExperienceBar(InGameHud:662)
    at net.minecraft.client.gui.hud.InGameHud.render(InGameHud:260)
    at net.minecraft.client.render.GameRenderer.render(GameRenderer:858)
    at net.minecraft.client.MinecraftClient.render(MinecraftClient:1122)
    at net.minecraft.client.MinecraftClient.run(MinecraftClient:737)
    at net.minecraft.client.main.Main.main(Main:236)
    at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:460)
    at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
    at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

**Comment by burgerindividual** [comment]
I can't really do anything about mods inject-cancelling before a pop happens. I tried to see if I could replicate a try-finally, but that didn't work. The only way this would be feasible would be to move away from mixin entirely and use ASM, which is a huge pain and breaks between versions more.

The mod in question could implement HUDTweaks-api and put its own elements there, removing the vanilla entries, but I don't really have the time to do it for them at the moment.
